### ISSUE TITLE
How can I determine the Grasping quality?

### ISSUE THREAD

**Issue by LemonQC** [andvg3/Grasp-Anything#5]
Can you share the implementations of the following equation.
![image](https://github.com/andvg3/Grasp-Anything/assets/30914380/7b0afb58-b9e0-49a8-be10-355cc2a3d8cc)

**Comment by andvg3** [comment]
Dear @LemonQC,

Thank you for your interest in our research. Regarding your query about equation (1) in our paper, its implementation is complex due to the indeterminate physical properties of the objects, as mentioned in our paper:

"Due to the impracticality of explicitly determining the physical terms for each object [56], the computation of T becomes infeasible without knowing the physical parameters M, K, μs. We employ the following concept to address the challenges posed by physical constraints ..."

We utilize equation (2) as a substitute for this grasp evaluation.

Please note, the repository does not include code for creating the Grasp-Anything dataset, and the grasp evaluation method's implementation is part of this code. Hence, this repository won't directly address your question.

We are considering releasing the code for the Grasp-Anything dataset in the future, which will include the grasp quality evaluation implementation. Stay updated for further developments.

Best regards.

**Comment by andvg3** [comment]
Closed due to inactivity.
