### ISSUE TITLE
How about the quality of grasp poses annotatation for each object using a pretrained model RAGT-3/3?

### ISSUE THREAD

**Issue by andyoung009** [andvg3/Grasp-Anything#7]
Hi, it is a nice work. I am interested in it. I want to know the  the quality of grasp poses annotatation for each object using a pretrained model RAGT-3/3. Is there domain gap between the sence in your dataset generated by the scene description and the RAGT-3/3 dataset? I used the RAGT-3/3 pretrain model to test on a random scene picture, the results were not so good! Would you please give some details on this pipeline? Thanks!
<img width="147" alt="1" src="https://github.com/andvg3/Grasp-Anything/assets/125349112/e0a3e1be-d5ee-4951-9599-248c3264bea3">

**Comment by andvg3** [comment]
Hi @andyoung009,

> I want to know the the quality of grasp poses annotatation for each object using a pretrained model RAGT-3/3

Before generating grasp poses of a specific object in the scene, we mask out the object first and then use the masked image to generate grasp poses (specified in Section III-A of our paper). Therefore, the generated grasp poses by a pretrained RAGT-3/3 model are usually acceptable. To further improve the quality of generated grasp poses, we employ a grasp evaluation procedure, which is described in Section III-B of our paper.

> Is there domain gap between the sence in your dataset generated by the scene description and the (NBMOD) dataset?

The objects generated in Grasp-Anything and real objects in the NBMOD may possess some domain gap. In fact, because of this, we have to evaluate whether our data could be useful in actual robotic experiments or not. There is a hypothesis in our experiment section: "_Since our dataset is generated by the foundation models, will it work on real robot experiments?_" We demonstrate that policy that is trained on Grasp-Anything can result in meaningful grasp operations in real robot experiments.

I hope my answers are helpful. Thank you for your interest in our work, and looking forward to addressing any further questions you may have.
Best regards,
An Vuong

**Comment by andyoung009** [comment]
Thank you very much! 

> mask out the object first and then use the masked image to generate grasp poses (specified in Section III-A of our paper)

How can the masked image  generate acceptable grasp poses? Is there any other constraints before the grasp evaluation procedure described in Section III-B of your paper?  I just use the  the pretrained RAGT-3/3 model for some common scene pictures, the results seems not so good.

Thank you.

**Comment by andvg3** [comment]
Hi @andyoung009,

The masked image focuses on the visual information of the target object; therefore, intuitively, generated grasp poses from masked images will attach more to the target object than directly from the images. Of course, while it is not explicitly possible to evaluate the quality of grasp poses, we do study whether our synthetic dataset is useful or not, particularly in real robot experiments.

Thank you for your interests. I hope my explanations are helpful and look forward to your respones.
Best regards,
An Vuong

**Comment by andvg3** [comment]
Closed due to inactivity,
